<!-- resources/views/absensi-gerbang/export-pdf.blade.php -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTitle }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .logo {
            width: 80px;
            height: auto;
            margin-bottom: 10px;
        }
        h1 {
            font-size: 20px;
            margin: 5px 0;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        h2 {
            font-size: 16px;
            margin: 5px 0;
            color: #333;
        }
        .info {
            margin-bottom: 20px;
            padding: 12px;
            background-color: #f9f9f9;
            border-radius: 5px;
            border: 1px solid #ddd;
        }
        .info-title {
            font-weight: bold;
            margin-bottom: 8px;
            color: #333;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #000;
            padding: 6px;
            font-size: 11px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 10px;
        }
        .date-header {
            background-color: #e9ecef;
            font-weight: bold;
            padding: 10px;
            margin-top: 20px;
            margin-bottom: 8px;
            border-radius: 5px;
            border-left: 5px solid #5a5a5a;
        }
        .statistics {
            margin-top: 25px;
            padding: 15px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 5px;
            page-break-inside: avoid;
        }
        .statistics-title {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 10px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        .footer {
            margin-top: 40px;
            text-align: right;
            font-size: 10px;
            color: #555;
            border-top: 1px solid #ddd;
            padding-top: 15px;
            clear: both;
        }
        .page-break {
            page-break-after: always;
        }
        .status-hadir {
            color: green;
            font-weight: bold;
        }
        .status-terlambat {
            color: orange;
            font-weight: bold;
        }
        .status-alpha {
            color: red;
            font-weight: bold;
        }
        .no-data {
            text-align: center;
            padding: 30px;
            font-style: italic;
            color: #777;
            border: 1px dashed #ddd;
            margin: 20px 0;
        }
        .stats-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        .stats-label {
            width: 60%;
            font-weight: normal;
        }
        .stats-value {
            width: 40%;
            text-align: right;
        }
        .clearance {
            clear: both;
            margin-top: 40px;
            page-break-inside: avoid;
        }
        .signature {
            width: 40%;
            float: right;
            text-align: center;
            margin-top: 20px;
        }
        .signature-line {
            border-top: 1px solid #000;
            margin-top: 40px;
            width: 80%;
            display: inline-block;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .report-subtitle {
            font-size: 12px;
            color: #555;
            margin-top: 5px;
        }
        .watermark {
            position: fixed;
            bottom: 0;
            left: 0;
            font-size: 8px;
            color: #ddd;
            width: 100%;
            text-align: center;
            z-index: -1000;
        }
    </style>
</head>
<body>
    <div class="watermark">Generated by: {{ Auth::user()->name ?? 'System' }} - {{ now()->format('d-m-Y H:i:s') }}</div>

    <div class="header">
        <h1>LAPORAN ABSENSI GERBANG</h1>
        <h2>{{ $reportTitle }}</h2>
        <p class="report-subtitle">Periode: {{ $statistics['startDate']->format('d-m-Y') }} s/d {{ $statistics['endDate']->format('d-m-Y') }}</p>
    </div>

    <div class="info">
        <div class="info-title">Statistik Absensi:</div>
        <table style="width: 100%; border: none;">
            <tr style="border: none;">
                <td style="border: none; width: 60%; padding: 3px;">Total Data Absensi</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['totalRecords'] }}</td>
            </tr>
            <tr style="border: none;">
                <td style="border: none; padding: 3px;">Siswa</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['siswaCount'] }} ({{ $statistics['totalRecords'] > 0 ? round(($statistics['siswaCount'] / $statistics['totalRecords']) * 100, 2) : 0 }}%)</td>
            </tr>
            <tr style="border: none;">
                <td style="border: none; padding: 3px;">Karyawan</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['karyawanCount'] }} ({{ $statistics['totalRecords'] > 0 ? round(($statistics['karyawanCount'] / $statistics['totalRecords']) * 100, 2) : 0 }}%)</td>
            </tr>
            <tr style="border: none;">
                <td style="border: none; padding: 3px;">Absensi Lengkap (Masuk & Keluar)</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['completeAttendance'] }} ({{ $statistics['totalRecords'] > 0 ? round(($statistics['completeAttendance'] / $statistics['totalRecords']) * 100, 2) : 0 }}%)</td>
            </tr>
            <tr style="border: none;">
                <td style="border: none; padding: 3px;">Absensi Tidak Lengkap (Hanya Masuk)</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['incompleteAttendance'] }} ({{ $statistics['totalRecords'] > 0 ? round(($statistics['incompleteAttendance'] / $statistics['totalRecords']) * 100, 2) : 0 }}%)</td>
            </tr>
        </table>
    </div>

    @if($groupedData->count() > 0)
        @foreach($groupedData as $date => $records)
            <div class="date-header">
                Tanggal: {{ \Carbon\Carbon::parse($date)->format('d F Y') }} ({{ \Carbon\Carbon::parse($date)->isoFormat('dddd') }})
            </div>

            <table>
                <thead>
                    <tr>
                        <th style="width: 5%; text-align: center;">No</th>
                        <th style="width: 20%;">Nama</th>
                        <th style="width: 10%;">Kategori</th>
                        <th style="width: 12%;">Waktu Masuk</th>
                        <th style="width: 12%;">Waktu Keluar</th>
                        <th style="width: 8%; text-align: center;">Status</th>
                        <th style="width: 33%;">Informasi Tambahan</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($records as $index => $record)
                        <tr>
                            <td style="text-align: center;">{{ $index + 1 }}</td>
                            <td>
                                @if($record->siswa)
                                    {{ $record->siswa->nama_lengkap }}
                                @elseif($record->karyawan)
                                    {{ $record->karyawan->nama_lengkap }}
                                @else
                                    Data tidak tersedia
                                @endif
                            </td>
                            <td>
                                @if($record->siswa)
                                    Siswa
                                @elseif($record->karyawan)
                                    Karyawan
                                    @if($record->karyawan->jabatan)
                                        <br><small>({{ $record->karyawan->jabatan }})</small>
                                    @endif
                                @else
                                    -
                                @endif
                            </td>
                            <td>{{ $record->waktu_scan_masuk }}</td>
                            <td>{{ $record->waktu_scan_keluar ?? '-' }}</td>
                            <td style="text-align: center;">
                                @if($record->status == 'Hadir')
                                    <span class="status-hadir">Hadir</span>
                                @elseif($record->status == 'Terlambat')
                                    <span class="status-terlambat">Terlambat</span>
                                @elseif($record->status == 'Alpha')
                                    <span class="status-alpha">Alpha</span>
                                @else
                                    {{ $record->status }}
                                @endif
                            </td>
                            <td>
                                <small>
                                    @if($record->jadwal)
                                        <strong>Jadwal:</strong> {{ $record->jadwal->nama_jadwal }}<br>
                                    @endif
                                    <strong>Discan oleh:</strong> {{ $record->scannedBy->name ?? 'System' }}<br>
                                    @if($record->siswa && $record->siswa->kelas)
                                        <strong>Kelas:</strong> {{ $record->siswa->kelas }}
                                    @endif
                                </small>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            @if(!$loop->last)
                <div class="page-break"></div>
            @endif
        @endforeach
    @else
        <div class="no-data">
            Tidak ada data absensi untuk periode yang dipilih.
        </div>
    @endif

    <div class="statistics">
        <div class="statistics-title">Rekapitulasi Absensi</div>
        <table style="width: 100%; border: none; margin-bottom: 5px;">
            <tr style="border: none; background-color: transparent;">
                <td style="border: none; width: 60%; padding: 3px;">Total Data Absensi</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['totalRecords'] }}</td>
            </tr>
            <tr style="border: none; background-color: transparent;">
                <td style="border: none; padding: 3px;">Total Siswa</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['siswaCount'] }} ({{ $statistics['totalRecords'] > 0 ? round(($statistics['siswaCount'] / $statistics['totalRecords']) * 100, 2) : 0 }}%)</td>
            </tr>
            <tr style="border: none; background-color: transparent;">
                <td style="border: none; padding: 3px;">Total Karyawan</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['karyawanCount'] }} ({{ $statistics['totalRecords'] > 0 ? round(($statistics['karyawanCount'] / $statistics['totalRecords']) * 100, 2) : 0 }}%)</td>
            </tr>
            <tr style="border: none; background-color: transparent;">
                <td style="border: none; padding: 3px;">Absensi Lengkap</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['completeAttendance'] }} ({{ $statistics['totalRecords'] > 0 ? round(($statistics['completeAttendance'] / $statistics['totalRecords']) * 100, 2) : 0 }}%)</td>
            </tr>
            <tr style="border: none; background-color: transparent;">
                <td style="border: none; padding: 3px;">Absensi Tidak Lengkap</td>
                <td style="border: none; padding: 3px;">: {{ $statistics['incompleteAttendance'] }} ({{ $statistics['totalRecords'] > 0 ? round(($statistics['incompleteAttendance'] / $statistics['totalRecords']) * 100, 2) : 0 }}%)</td>
            </tr>
        </table>
    </div>

    <div class="clearance">
        <div class="signature">
            Bandung, {{ now()->format('d F Y') }}<br>
            <strong>Petugas</strong><br><br><br>
            <span class="signature-line"></span>
        </div>
    </div>

    <div class="footer">
        Dicetak pada: {{ now()->format('d-m-Y H:i:s') }} | Sistem Absensi SMK IGASAR
    </div>
</body>
</html>

